# This is an OVERRIDE compose file for production deployment
# run with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

configs:
  caddyfile:
    content: |
      # Caddyfile for production Mastodon deployment
      # Uses automatic HTTPS with Let's Encrypt

       ${LOCAL_DOMAIN}  {
        # Automatic HTTPS with Let's Encrypt (default behavior)
        # No tls directive needed - Caddy handles it automatically

        # Reverse proxy to Mastodon web service
        reverse_proxy web:3000

        # Enable logging
        log {
          output stdout
          level INFO
        }

        # Production security headers
        header {
          # Security headers
          X-Frame-Options "DENY"
          X-Content-Type-Options "nosniff"
          X-XSS-Protection "1; mode=block"
          Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
          Referrer-Policy "strict-origin-when-cross-origin"

          # Remove server identification
          -Server
        }

        # Enable compression
        encode gzip zstd
      }
