name: Image digest update

on:
  workflow_dispatch:
  schedule:
    # At the end of every day
    - cron: "0 0 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: write # to push the updates
      pull-requests: write # to open Pull requests
      id-token: write # used to sign the commits using gitsign

  
    steps:
      - uses: actions/checkout@v5.0.0
      
      - uses: chainguard-dev/digestabot@v1.2.3        
        with:
          create-pr: true
